x = [{'object': 'page', 'id': '22ad06fc-f646-814b-8375-c6c2a032abda', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-07-08T20:19:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '+7 988 812-88-20'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 3}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Тамила', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Тамила', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 13},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': '+7 918 811-32-22'},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Обучается Python тг-боты', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Обучается Python тг-боты',
                          'href': None}]}, 'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                                                'date': {'start': '2024-11-18', 'end': None,
                                                                         'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': 'a6d6b0ce-3cf1-4111-a2a5-98a04afe9e7d', 'name': 'Назрань',
                                          'color': 'blue'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select',
                               'select': {'id': 'b1b9bd98-622b-489d-b623-91574f7ce056', 'name': 'Индивидуально 1 раз',
                                          'color': 'green'}}, 'ФИО': {'id': 'title', 'type': 'title', 'title': [
              {'type': 'text', 'text': {'content': 'Хашагульгов Расул Сулиманович', 'link': None},
               'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                               'code': False, 'color': 'default'}, 'plain_text': 'Хашагульгов Расул Сулиманович',
               'href': None}]}}, 'url': 'https://www.notion.so/22ad06fcf646814b8375c6c2a032abda', 'public_url': None},
     {'object': 'page', 'id': '22ad06fc-f646-8174-9a01-f230032574ac', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-07-08T20:19:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '89888242071'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 5}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Ибрагим', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Ибрагим', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 13},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': '89888293737'},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Учится Scratch', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Учится Scratch',
                          'href': None}]}, 'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                                                'date': {'start': '2025-03-03', 'end': None,
                                                                         'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': 'a6d6b0ce-3cf1-4111-a2a5-98a04afe9e7d', 'name': 'Назрань',
                                          'color': 'blue'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select',
                               'select': {'id': '7ea00347-b06c-4e95-a6b4-56ca896cf6d4', 'name': 'Группа 1 раз',
                                          'color': 'gray'}}, 'ФИО': {'id': 'title', 'type': 'title', 'title': [
              {'type': 'text', 'text': {'content': 'Султыгов Мухаммад Ибрагимович', 'link': None},
               'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                               'code': False, 'color': 'default'}, 'plain_text': 'Султыгов Мухаммад Ибрагимович',
               'href': None}]}}, 'url': 'https://www.notion.so/22ad06fcf64681749a01f230032574ac', 'public_url': None},
     {'object': 'page', 'id': '22ad06fc-f646-8194-86ca-f709a9660f97', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-08-05T14:51:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '89931710999'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 2}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Эльберт', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Эльберт', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 13},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': '89993300664'},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Обучается Python ', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Обучается Python ',
                          'href': None}]}, 'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                                                'date': {'start': '2025-06-04', 'end': None,
                                                                         'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': '135bb620-0470-434d-b27b-253b6d7d6ca9', 'name': 'Магас',
                                          'color': 'red'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select',
                               'select': {'id': 'b1b9bd98-622b-489d-b623-91574f7ce056', 'name': 'Индивидуально 1 раз',
                                          'color': 'green'}}, 'ФИО': {'id': 'title', 'type': 'title', 'title': [
              {'type': 'text', 'text': {'content': 'Яндиев Муслим Эльбертович', 'link': None},
               'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                               'code': False, 'color': 'default'}, 'plain_text': 'Яндиев Муслим Эльбертович',
               'href': None}]}}, 'url': 'https://www.notion.so/22ad06fcf646819486caf709a9660f97', 'public_url': None},
     {'object': 'page', 'id': '22ad06fc-f646-81b7-98d3-cdf06de48a66', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-07-08T20:19:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '89623331909'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 1}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Назир', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Назир', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 20},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': 'https://t.me/Abu_Alonse'},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': []},
                     'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                          'date': {'start': '2025-05-29', 'end': None, 'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select', 'select': None},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select', 'select': None}, 'ФИО': {'id': 'title', 'type': 'title',
                                                                                        'title': [{'type': 'text',
                                                                                                   'text': {
                                                                                                       'content': 'Сусуркиев Абдул-Азиз Назирович',
                                                                                                       'link': None},
                                                                                                   'annotations': {
                                                                                                       'bold': False,
                                                                                                       'italic': False,
                                                                                                       'strikethrough': False,
                                                                                                       'underline': False,
                                                                                                       'code': False,
                                                                                                       'color': 'default'},
                                                                                                   'plain_text': 'Сусуркиев Абдул-Азиз Назирович',
                                                                                                   'href': None}]}},
      'url': 'https://www.notion.so/22ad06fcf64681b798d3cdf06de48a66', 'public_url': None},
     {'object': 'page', 'id': '22ad06fc-f646-81c7-b1bf-d65cc5916083', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-07-08T20:19:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '89287902366'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 6}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Мухаммад', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Мухаммад', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 11},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': None},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Учит Scratch', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Учит Scratch',
                          'href': None}]}, 'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                                                'date': {'start': '2025-06-21', 'end': None,
                                                                         'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': 'a6d6b0ce-3cf1-4111-a2a5-98a04afe9e7d', 'name': 'Назрань',
                                          'color': 'blue'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select',
                               'select': {'id': '54312853-e8ec-4f3a-94ff-94510a50161f', 'name': 'Группа 2 раза',
                                          'color': 'yellow'}}, 'ФИО': {'id': 'title', 'type': 'title', 'title': [
              {'type': 'text', 'text': {'content': 'Оздоев Али Тимерланович', 'link': None},
               'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                               'code': False, 'color': 'default'}, 'plain_text': 'Оздоев Али Тимерланович',
               'href': None}]}}, 'url': 'https://www.notion.so/22ad06fcf64681c7b1bfd65cc5916083', 'public_url': None},
     {'object': 'page', 'id': '22ad06fc-f646-81da-8a71-ea614579e17c', 'created_time': '2025-07-08T20:19:00.000Z',
      'last_edited_time': '2025-07-08T20:19:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '89287902366'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 4}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Мухаммад', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Мухаммад', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 16},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select',
                                'select': {'id': '5016de11-3f71-47a7-80f5-d8fe600c224c', 'name': 'Обучается',
                                           'color': 'green'}},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': '89280958651'},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Обучается JS на кодбасик', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Обучается JS на кодбасик',
                          'href': None}]}, 'Дата поступления': {'id': '%5BTnQ', 'type': 'date',
                                                                'date': {'start': '2025-01-09', 'end': None,
                                                                         'time_zone': None}},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': 'a6d6b0ce-3cf1-4111-a2a5-98a04afe9e7d', 'name': 'Назрань',
                                          'color': 'blue'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select',
                               'select': {'id': '54312853-e8ec-4f3a-94ff-94510a50161f', 'name': 'Группа 2 раза',
                                          'color': 'yellow'}}, 'ФИО': {'id': 'title', 'type': 'title', 'title': [
              {'type': 'text', 'text': {'content': 'Газгиреев Абубакар Мухаммадович', 'link': None},
               'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                               'code': False, 'color': 'default'}, 'plain_text': 'Газгиреев Абубакар Мухаммадович',
               'href': None}]}}, 'url': 'https://www.notion.so/22ad06fcf64681da8a71ea614579e17c', 'public_url': None},
     {'object': 'page', 'id': '253d06fc-f646-80cb-a55c-e25eaf5cee34', 'created_time': '2025-08-18T08:38:00.000Z',
      'last_edited_time': '2025-08-18T08:39:00.000Z',
      'created_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'},
      'last_edited_by': {'object': 'user', 'id': '200d872b-594c-8161-a594-0002bb20888b'}, 'cover': None, 'icon': None,
      'parent': {'type': 'database_id', 'database_id': '22ad06fc-f646-8128-a827-c7d0bddd18c1'}, 'archived': False,
      'in_trash': False, 'is_locked': False,
      'properties': {'Номер родителя': {'id': '%3A%40%7BK', 'type': 'phone_number', 'phone_number': '79287411756'},
                     'ID': {'id': '%3EPAi', 'type': 'unique_id', 'unique_id': {'prefix': None, 'number': 7}},
                     'Имя родителя': {'id': 'DWML', 'type': 'rich_text', 'rich_text': [
                         {'type': 'text', 'text': {'content': 'Мадина', 'link': None},
                          'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False,
                                          'code': False, 'color': 'default'}, 'plain_text': 'Мадина', 'href': None}]},
                     'Возраст': {'id': 'HsEl', 'type': 'number', 'number': 16},
                     'Статус': {'id': 'N%5By%7B', 'type': 'select', 'select': None},
                     'Ссылка на WA, TG': {'id': 'PiUY', 'type': 'url', 'url': None},
                     'Комментарий': {'id': '%5BEvu', 'type': 'rich_text', 'rich_text': []},
                     'Дата поступления': {'id': '%5BTnQ', 'type': 'date', 'date': None},
                     'Город': {'id': 'p%3AdX', 'type': 'select',
                               'select': {'id': 'a6d6b0ce-3cf1-4111-a2a5-98a04afe9e7d', 'name': 'Назрань',
                                          'color': 'blue'}},
                     'Группа': {'id': 'wVjg', 'type': 'relation', 'relation': [], 'has_more': False},
                     'Тариф': {'id': 'wdMG', 'type': 'select', 'select': None}, 'ФИО': {'id': 'title', 'type': 'title',
                                                                                        'title': [{'type': 'text',
                                                                                                   'text': {
                                                                                                       'content': 'Кодзоев Магомед-Амин Адамович',
                                                                                                       'link': None},
                                                                                                   'annotations': {
                                                                                                       'bold': False,
                                                                                                       'italic': False,
                                                                                                       'strikethrough': False,
                                                                                                       'underline': False,
                                                                                                       'code': False,
                                                                                                       'color': 'default'},
                                                                                                   'plain_text': 'Кодзоев Магомед-Амин Адамович',
                                                                                                   'href': None}]}},
      'url': 'https://www.notion.so/253d06fcf64680cba55ce25eaf5cee34', 'public_url': None}]
